/**
 * EOD Report Submitted Email Template (React Component)
 * This is a preview component for the email template
 * The actual email is generated by getEodReportSubmittedEmailHTML()
 */

export type EodReportSubmittedEmailData = {
  employeeName: string;
  employeeEmail: string;
  ventureName: string;
  officeName?: string;
  reportDate: string;
  summary: string;
  accomplishments?: string;
  blockers?: string;
  tomorrowPlan?: string;
  hoursWorked?: number;
  tasksCompleted?: number;
  attendanceStatus?: string;
  attendanceMarkedAt?: string;
  attendanceUpdatedAt?: string;
  reportUrl: string;
};

interface Props {
  employeeName: string;
  employeeEmail: string;
  ventureName: string;
  officeName?: string;
  reportDate: string;
  summary: string;
  accomplishments?: string;
  blockers?: string;
  tomorrowPlan?: string;
  hoursWorked?: number;
  tasksCompleted?: number;
  attendanceStatus?: string;
  attendanceMarkedAt?: string;
  attendanceUpdatedAt?: string;
  reportUrl: string;
}

function formatTimestampWithTimezone(isoString: string): string {
  try {
    const date = new Date(isoString);
    // Format as: "YYYY-MM-DD HH:MM:SS UTC" for clarity
    const utcStr = date.toISOString();
    const utcDate = utcStr.substring(0, 19).replace('T', ' ') + ' UTC';
    // Also include ISO format for reference
    return `${utcDate} (${utcStr})`;
  } catch {
    return isoString;
  }
}

export default function EodReportSubmittedEmailTemplate({
  employeeName,
  employeeEmail,
  ventureName,
  officeName,
  reportDate,
  summary,
  accomplishments,
  blockers,
  tomorrowPlan,
  hoursWorked,
  tasksCompleted,
  attendanceStatus,
  attendanceMarkedAt,
  attendanceUpdatedAt,
  reportUrl,
}: Props) {
  const markedTimeFormatted = attendanceMarkedAt ? formatTimestampWithTimezone(attendanceMarkedAt) : null;
  const updatedTimeFormatted = attendanceUpdatedAt ? formatTimestampWithTimezone(attendanceUpdatedAt) : null;
  const wasUpdated = attendanceUpdatedAt && attendanceMarkedAt && 
    new Date(attendanceUpdatedAt).getTime() > new Date(attendanceMarkedAt).getTime() + 1000;
  return (
    <div style={{ fontFamily: 'Arial, sans-serif', maxWidth: '600px', margin: '0 auto', padding: '40px 20px' }}>
      <div style={{ backgroundColor: '#ffffff', borderRadius: '12px', padding: '40px 30px' }}>
        {/* Header */}
        <div style={{ textAlign: 'center', marginBottom: '30px' }}>
          <h1 style={{ color: '#111827', fontSize: '24px', fontWeight: 'bold', margin: '0 0 10px 0' }}>
            New EOD Report Submitted
          </h1>
          <div style={{ width: '60px', height: '3px', backgroundColor: '#3b82f6', margin: '0 auto' }}></div>
        </div>

        {/* Greeting */}
        <p style={{ color: '#374151', fontSize: '16px', lineHeight: '24px', margin: '0 0 20px 0' }}>Hello,</p>
        <p style={{ color: '#374151', fontSize: '16px', lineHeight: '24px', margin: '0 0 30px 0' }}>
          An employee has submitted their End of Day report. Please review the details below:
        </p>

        {/* Employee Info Box */}
        <div
          style={{
            backgroundColor: '#f0f9ff',
            border: '1px solid #3b82f6',
            borderRadius: '12px',
            padding: '24px',
            margin: '0 0 30px 0',
            borderLeft: '4px solid #3b82f6',
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '16px' }}>
            <div
              style={{
                width: '40px',
                height: '40px',
                backgroundColor: '#3b82f6',
                borderRadius: '50%',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              <span style={{ fontSize: '20px', color: '#ffffff' }}>📋</span>
            </div>
            <div>
              <h2 style={{ color: '#1e40af', fontSize: '18px', fontWeight: '600', margin: '0' }}>{reportDate}</h2>
              <p style={{ color: '#1e3a8a', fontSize: '14px', margin: '4px 0 0 0' }}>
                {ventureName}
                {officeName ? ` - ${officeName}` : ''}
              </p>
            </div>
          </div>
        </div>

        {/* Employee Details */}
        <div
          style={{
            backgroundColor: '#f9fafb',
            border: '1px solid #e5e7eb',
            borderRadius: '12px',
            padding: '24px',
            margin: '0 0 30px 0',
          }}
        >
          <h3 style={{ color: '#111827', fontSize: '18px', fontWeight: '600', margin: '0 0 20px 0' }}>
            Employee Information
          </h3>
          <table style={{ width: '100%', borderCollapse: 'collapse' }}>
            <tbody>
              <tr>
                <td
                  style={{
                    padding: '8px 0',
                    color: '#6b7280',
                    fontSize: '14px',
                    fontWeight: '600',
                    width: '120px',
                  }}
                >
                  Employee:
                </td>
                <td style={{ padding: '8px 0', color: '#111827', fontSize: '14px', fontWeight: '500' }}>
                  {employeeName}
                </td>
              </tr>
              <tr>
                <td style={{ padding: '8px 0', color: '#6b7280', fontSize: '14px', fontWeight: '600' }}>Email:</td>
                <td style={{ padding: '8px 0', color: '#111827', fontSize: '14px', fontWeight: '500' }}>
                  {employeeEmail}
                </td>
              </tr>
              <tr>
                <td style={{ padding: '8px 0', color: '#6b7280', fontSize: '14px', fontWeight: '600' }}>Venture:</td>
                <td style={{ padding: '8px 0', color: '#111827', fontSize: '14px', fontWeight: '500' }}>
                  {ventureName}
                </td>
              </tr>
              {officeName && (
                <tr>
                  <td style={{ padding: '8px 0', color: '#6b7280', fontSize: '14px', fontWeight: '600' }}>
                    Office:
                  </td>
                  <td style={{ padding: '8px 0', color: '#111827', fontSize: '14px', fontWeight: '500' }}>
                    {officeName}
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>

        {/* Attendance Information */}
        {attendanceStatus && (
          <div
            style={{
              backgroundColor: '#f0fdf4',
              border: '1px solid #22c55e',
              borderRadius: '12px',
              padding: '24px',
              margin: '0 0 30px 0',
              borderLeft: '4px solid #22c55e',
            }}
          >
            <h3
              style={{
                color: '#111827',
                fontSize: '18px',
                fontWeight: '600',
                margin: '0 0 20px 0',
                display: 'flex',
                alignItems: 'center',
                gap: '8px',
              }}
            >
              <span style={{ fontSize: '20px' }}>📅</span>
              Attendance Information
            </h3>
            <table style={{ width: '100%', borderCollapse: 'collapse' }}>
              <tbody>
                <tr>
                  <td
                    style={{
                      padding: '8px 0',
                      color: '#6b7280',
                      fontSize: '14px',
                      fontWeight: '600',
                      width: '150px',
                    }}
                  >
                    Status:
                  </td>
                  <td style={{ padding: '8px 0', color: '#111827', fontSize: '14px', fontWeight: '500' }}>
                    <span
                      style={{
                        display: 'inline-block',
                        padding: '4px 12px',
                        borderRadius: '6px',
                        fontSize: '13px',
                        fontWeight: '600',
                        backgroundColor: '#dcfce7',
                        color: '#166534',
                      }}
                    >
                      {attendanceStatus}
                    </span>
                  </td>
                </tr>
                {markedTimeFormatted && (
                  <tr>
                    <td style={{ padding: '8px 0', color: '#6b7280', fontSize: '14px', fontWeight: '600' }}>
                      Marked At:
                    </td>
                    <td style={{ padding: '8px 0', color: '#111827', fontSize: '14px', fontWeight: '500' }}>
                      {markedTimeFormatted}
                    </td>
                  </tr>
                )}
                {wasUpdated && updatedTimeFormatted && (
                  <tr>
                    <td style={{ padding: '8px 0', color: '#6b7280', fontSize: '14px', fontWeight: '600' }}>
                      Updated At:
                    </td>
                    <td style={{ padding: '8px 0', color: '#111827', fontSize: '14px', fontWeight: '500' }}>
                      {updatedTimeFormatted}
                      <span style={{ color: '#f59e0b', fontSize: '12px', marginLeft: '8px' }}>
                        (Status Changed)
                      </span>
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
            {markedTimeFormatted && (
              <p
                style={{
                  color: '#6b7280',
                  fontSize: '12px',
                  margin: '12px 0 0 0',
                  fontStyle: 'italic',
                }}
              >
                All timestamps are stored in UTC (Coordinated Universal Time) for accuracy. Times shown are in UTC
                format (ISO 8601) which is timezone-independent and accurate for users in any location (India, US,
                etc.).
              </p>
            )}
          </div>
        )}

        {/* Report Summary */}
        <div
          style={{
            backgroundColor: '#ffffff',
            border: '1px solid #e5e7eb',
            borderRadius: '12px',
            padding: '24px',
            margin: '0 0 30px 0',
          }}
        >
          <h3 style={{ color: '#111827', fontSize: '18px', fontWeight: '600', margin: '0 0 16px 0' }}>Summary</h3>
          <div
            style={{
              color: '#4b5563',
              fontSize: '15px',
              lineHeight: '24px',
              padding: '16px',
              backgroundColor: '#f9fafb',
              borderRadius: '8px',
              border: '1px solid #e5e7eb',
              whiteSpace: 'pre-wrap',
            }}
          >
            {summary}
          </div>
        </div>

        {/* Additional Details */}
        {(accomplishments || blockers || tomorrowPlan || hoursWorked !== null || tasksCompleted !== null) && (
          <div
            style={{
              backgroundColor: '#ffffff',
              border: '1px solid #e5e7eb',
              borderRadius: '12px',
              padding: '24px',
              margin: '0 0 30px 0',
            }}
          >
            <h3 style={{ color: '#111827', fontSize: '18px', fontWeight: '600', margin: '0 0 20px 0' }}>
              Additional Details
            </h3>
            <table style={{ width: '100%', borderCollapse: 'collapse' }}>
              <tbody>
                {hoursWorked !== null && (
                  <tr>
                    <td
                      style={{
                        padding: '8px 0',
                        color: '#6b7280',
                        fontSize: '14px',
                        fontWeight: '600',
                        width: '150px',
                      }}
                    >
                      Hours Worked:
                    </td>
                    <td style={{ padding: '8px 0', color: '#111827', fontSize: '14px', fontWeight: '500' }}>
                      {hoursWorked} hours
                    </td>
                  </tr>
                )}
                {tasksCompleted !== null && (
                  <tr>
                    <td style={{ padding: '8px 0', color: '#6b7280', fontSize: '14px', fontWeight: '600' }}>
                      Tasks Completed:
                    </td>
                    <td style={{ padding: '8px 0', color: '#111827', fontSize: '14px', fontWeight: '500' }}>
                      {tasksCompleted} task{tasksCompleted !== 1 ? 's' : ''}
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
            {accomplishments && (
              <div style={{ marginTop: '16px', paddingTop: '16px', borderTop: '1px solid #e5e7eb' }}>
                <h4 style={{ color: '#374151', fontSize: '15px', fontWeight: '600', margin: '0 0 8px 0' }}>
                  Accomplishments:
                </h4>
                <div
                  style={{
                    color: '#4b5563',
                    fontSize: '14px',
                    lineHeight: '22px',
                    whiteSpace: 'pre-wrap',
                  }}
                >
                  {accomplishments}
                </div>
              </div>
            )}
            {blockers && (
              <div style={{ marginTop: '16px', paddingTop: '16px', borderTop: '1px solid #e5e7eb' }}>
                <h4 style={{ color: '#374151', fontSize: '15px', fontWeight: '600', margin: '0 0 8px 0' }}>
                  Blockers:
                </h4>
                <div
                  style={{
                    color: '#4b5563',
                    fontSize: '14px',
                    lineHeight: '22px',
                    whiteSpace: 'pre-wrap',
                  }}
                >
                  {blockers}
                </div>
              </div>
            )}
            {tomorrowPlan && (
              <div style={{ marginTop: '16px', paddingTop: '16px', borderTop: '1px solid #e5e7eb' }}>
                <h4 style={{ color: '#374151', fontSize: '15px', fontWeight: '600', margin: '0 0 8px 0' }}>
                  Tomorrow's Plan:
                </h4>
                <div
                  style={{
                    color: '#4b5563',
                    fontSize: '14px',
                    lineHeight: '22px',
                    whiteSpace: 'pre-wrap',
                  }}
                >
                  {tomorrowPlan}
                </div>
              </div>
            )}
          </div>
        )}

        {/* CTA Button */}
        <div style={{ textAlign: 'center', margin: '0 0 30px 0' }}>
          <a
            href={reportUrl}
            style={{
              display: 'inline-block',
              backgroundColor: '#3b82f6',
              color: '#ffffff',
              padding: '14px 32px',
              textDecoration: 'none',
              borderRadius: '8px',
              fontSize: '16px',
              fontWeight: '600',
              boxShadow: '0 2px 4px rgba(59, 130, 246, 0.3)',
            }}
          >
            View Full Report
          </a>
        </div>

        {/* Footer */}
        <div
          style={{
            marginTop: '40px',
            paddingTop: '30px',
            borderTop: '1px solid #e5e7eb',
            textAlign: 'center',
          }}
        >
          <p style={{ color: '#6b7280', fontSize: '14px', lineHeight: '20px', margin: '0 0 8px 0' }}>
            Best regards,
          </p>
          <p style={{ color: '#111827', fontSize: '16px', fontWeight: '600', margin: '0' }}>SIOX Team</p>
        </div>
      </div>
    </div>
  );
}

