/**
 * Missed EOD Explanation Email Template (React Component)
 * This is a preview component for the email template
 * The actual email is generated by getMissedEodExplanationEmailHTML()
 */

export type MissedEodExplanationEmailData = {
  employeeName: string;
  employeeEmail: string;
  ventureName: string;
  consecutiveDays: number;
  missedDates: string[];
  explanation: string;
  explanationUrl: string;
};

interface Props {
  employeeName: string;
  employeeEmail: string;
  ventureName: string;
  consecutiveDays: number;
  missedDates: string[];
  explanation: string;
  explanationUrl: string;
}

export default function MissedEodExplanationEmailTemplate({
  employeeName,
  employeeEmail,
  ventureName,
  consecutiveDays,
  missedDates,
  explanation,
  explanationUrl,
}: Props) {
  const formattedDates = missedDates.join(', ');

  return (
    <div style={{ fontFamily: 'Arial, sans-serif', maxWidth: '600px', margin: '0 auto', padding: '40px 20px' }}>
      <div style={{ backgroundColor: '#ffffff', borderRadius: '12px', padding: '40px 30px' }}>
        {/* Header */}
        <div style={{ textAlign: 'center', marginBottom: '30px' }}>
          <h1 style={{ color: '#111827', fontSize: '24px', fontWeight: 'bold', margin: '0 0 10px 0' }}>
            Missed EOD Reports Notification
          </h1>
          <div style={{ width: '60px', height: '3px', backgroundColor: '#f59e0b', margin: '0 auto' }}></div>
        </div>

        {/* Greeting */}
        <p style={{ color: '#374151', fontSize: '16px', lineHeight: '24px', margin: '0 0 20px 0' }}>
          Hello,
        </p>
        <p style={{ color: '#374151', fontSize: '16px', lineHeight: '24px', margin: '0 0 30px 0' }}>
          An employee has submitted an explanation for missed EOD reports. Please review the details below:
        </p>

        {/* Alert Box */}
        <div
          style={{
            backgroundColor: '#fef3c7',
            border: '1px solid #f59e0b',
            borderRadius: '12px',
            padding: '24px',
            margin: '0 0 30px 0',
            borderLeft: '4px solid #f59e0b',
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '16px' }}>
            <div
              style={{
                width: '40px',
                height: '40px',
                backgroundColor: '#fbbf24',
                borderRadius: '50%',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              <span style={{ fontSize: '20px' }}>⚠️</span>
            </div>
            <div>
              <h2 style={{ color: '#92400e', fontSize: '18px', fontWeight: '600', margin: '0' }}>
                {consecutiveDays} Consecutive Day{consecutiveDays > 1 ? 's' : ''} Missed
              </h2>
              <p style={{ color: '#78350f', fontSize: '14px', margin: '4px 0 0 0' }}>{ventureName}</p>
            </div>
          </div>
        </div>

        {/* Employee Details */}
        <div
          style={{
            backgroundColor: '#f9fafb',
            border: '1px solid #e5e7eb',
            borderRadius: '12px',
            padding: '24px',
            margin: '0 0 30px 0',
          }}
        >
          <h3 style={{ color: '#111827', fontSize: '18px', fontWeight: '600', margin: '0 0 20px 0' }}>
            Employee Information
          </h3>
          <table style={{ width: '100%', borderCollapse: 'collapse' }}>
            <tbody>
              <tr>
                <td style={{ padding: '8px 0', color: '#6b7280', fontSize: '14px', fontWeight: '600', width: '120px' }}>
                  Employee:
                </td>
                <td style={{ padding: '8px 0', color: '#111827', fontSize: '14px', fontWeight: '500' }}>
                  {employeeName}
                </td>
              </tr>
              <tr>
                <td style={{ padding: '8px 0', color: '#6b7280', fontSize: '14px', fontWeight: '600' }}>Email:</td>
                <td style={{ padding: '8px 0', color: '#111827', fontSize: '14px', fontWeight: '500' }}>
                  {employeeEmail}
                </td>
              </tr>
              <tr>
                <td style={{ padding: '8px 0', color: '#6b7280', fontSize: '14px', fontWeight: '600' }}>Venture:</td>
                <td style={{ padding: '8px 0', color: '#111827', fontSize: '14px', fontWeight: '500' }}>
                  {ventureName}
                </td>
              </tr>
              <tr>
                <td
                  style={{
                    padding: '8px 0',
                    color: '#6b7280',
                    fontSize: '14px',
                    fontWeight: '600',
                    verticalAlign: 'top',
                  }}
                >
                  Missed Dates:
                </td>
                <td style={{ padding: '8px 0', color: '#111827', fontSize: '14px', fontWeight: '500' }}>
                  {formattedDates}
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        {/* Explanation */}
        <div
          style={{
            backgroundColor: '#ffffff',
            border: '1px solid #e5e7eb',
            borderRadius: '12px',
            padding: '24px',
            margin: '0 0 30px 0',
          }}
        >
          <h3 style={{ color: '#111827', fontSize: '18px', fontWeight: '600', margin: '0 0 16px 0' }}>
            Employee Explanation
          </h3>
          <div
            style={{
              color: '#4b5563',
              fontSize: '15px',
              lineHeight: '24px',
              padding: '16px',
              backgroundColor: '#f9fafb',
              borderRadius: '8px',
              border: '1px solid #e5e7eb',
              whiteSpace: 'pre-wrap',
            }}
          >
            {explanation}
          </div>
        </div>

        {/* CTA Button */}
        <div style={{ textAlign: 'center', margin: '0 0 30px 0' }}>
          <a
            href={explanationUrl}
            style={{
              display: 'inline-block',
              backgroundColor: '#f59e0b',
              color: '#ffffff',
              padding: '14px 32px',
              textDecoration: 'none',
              borderRadius: '8px',
              fontSize: '16px',
              fontWeight: '600',
              boxShadow: '0 2px 4px rgba(245, 158, 11, 0.3)',
            }}
          >
            Review Explanation
          </a>
        </div>

        {/* Footer */}
        <div
          style={{
            marginTop: '40px',
            paddingTop: '30px',
            borderTop: '1px solid #e5e7eb',
            textAlign: 'center',
          }}
        >
          <p style={{ color: '#6b7280', fontSize: '14px', lineHeight: '20px', margin: '0 0 8px 0' }}>
            Best regards,
          </p>
          <p style={{ color: '#111827', fontSize: '16px', fontWeight: '600', margin: '0' }}>SIOX Team</p>
        </div>
      </div>
    </div>
  );
}

